name: ChestShop
main: ChestShop\ChestShop
version: 2.1.0
api: [3.0.0-ALPHA11]
load: POSTWORLD
author: MinecrafterJPN
description: Open your ChestShop
website: https://github.com/MinecrafterJPN/ChestShop
depend:
 - PocketMoney
commands:
 id:
  description: Search item ID
  usage: "/id <itemname>"
  permission: chestshop.command.id
permissions:
 chestshop:
  default: op
  description: "Allows using all the ChestShop things"
  children:
   chestshop.command:
    default: op
    description: "Allows using all the PocketMoney commands"
    children:
     chestshop.command.id:
      default: true
      description: "Allows searching item ID"